# action builds and pushes the satic files to build branch

name: Bun.sh CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - name: get the master branch
      uses: actions/checkout@v4
      with:
        ref: master
        path: master
    - name: get the builds branch
      uses: actions/checkout@v4
      with:
        ref: builds
        path: builds
    - name: change to master
      run: |
        tree
        cd master
        tree
        pwd
        HOME=$(pwd)
    - name: Note The Time
      run: |
        echo "date = $(date)" >> $GITHUB_ENV 
    - name: Setup Bun Runtime
      uses: antongolub/action-setup-bun@v1 # or @v1.x.x
      with:
        token: ${{ github.token }}
      env:
        HOME: '/home/runner/work/spricklerUI/spricklerUI/master'
    - run: bun install
    - run: bun run build
    - name: exit master make builds dir
      run: |
        cd ..
        cd builds
    - name: copy the buils
      run: |
        ls ..
        cp ../master/dist .
    - name: push static files
      uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        name: ${{ github.actor }}
        commit_message: build ${{ env.date }}
        files: dist
        remote_repository: https://github.com/Notliam99/spricklerUI
        access_token: ${{ github.token }}
