# action builds and pushes the satic files to build branch

name: Bun.sh CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: get the master branch
      uses: actions/checkout@v4
      with:
        ref: master
    
    - name: setup bun.sh
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest 
    
    - run: bun install && bun run build

    - name: commit.sha
      run: echo "${{ github.sha }}" > ./dist/github.sha.txt
  
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}
        path: ./dist
  Push:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
    - name: get the builds branch
      uses: actions/checkout@v4
      with:
        ref: builds
    
    - name: get time
      run: echo "DATE = $(date)" > $GITHUB_ENV
    - uses: actions/download-artifact@v4
      with:
        name: ${{ github.sha }}
        path: ./dist
     
    - uses: actions4git/setup-git@v1 
    - run: |
        git add .
        git commit -m 'autopush ${{ env.DATE }}'
        git push
