# action builds and pushes the satic files to build branch

name: Bun.sh CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: builds
    - name: Note The Time
      run: |
        echo "date = $(date)" >> $GITHUB_ENV
    - name: get files
      env: 
        token: ${{ github.token }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git checkout master -- .
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install
    - run: bun run build
    - name: push static files
      uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        name: ${{ github.actor }}
        commit_message: build ${{ env.date }}
        files: dist
        remote_repository: https://github.com/Notliam99/spricklerUI
        access_token: ${{ github.token }}
