# action builds and pushes the satic files to build branch

name: Bun.sh CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Note The Time
      run: |
        echo "date = $(date)" >> $GITHUB_ENV
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install
    - run: bun run build
    - name: push static files
      uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        name: ${{ github.actor }}
        commit_message: build ${{ env.date }}
        target_branch: builds
        files: ./dist/
        access_token: ${{ github.token }}
