# action builds and pushes the satic files to build branch

name: Bun.sh CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Note The Time
      run: |
        echo "DATE = $(date)" >> $GITHUB_ENV
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install
    - run: bun run build
    - name: get files
      env: 
        token: ${{ github.token }}
      run: |
        git config --global credential.helper '!f() { sleep 1; echo "username=${{ github.actor }} token=${{ github.token }}"; }; f'
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        cp ./dist ./public -r
        git add public
        git commit -m "build@(${{ env.DATE }})"
        git push origin/builds
